#!/bin/bash
output=$(osascript -e '
if application "Spotify" is running then
  tell application "Spotify"
    if player state is playing then
      return artist of current track & " - " & name of current track
    end if
  end tell
end if
')
[ -n "$output" ] && echo "$output"

