require('sheena.core.mappings')
require('sheena.plugins')
require('sheena.plugins.default')
require('sheena.plugins.indentline')
require('sheena.plugins.nvimtree')
-- require('sheena.plugins.gotoworkspace')
require('sheena.plugins.telescope')
require('sheena.plugins.cmp')
require('sheena.lspconfig')()
require('sheena.plugins.treesitter')
require('sheena.plugins.lualine')
require('sheena.core.settings')
require('sheena.theme.catppucin')
require('sheena.plugins.flutter')
