# BPKP
[[session]]
name = "bpkb"
path = "~/Documents/Code/my-project/bpkb/bisma_be_dev"
startup_command = "update_tmux_window_name"
windows = ["docs", "database", "bisma_fe", "bisma_old"]

[[window]]
name = "docs"
startup_script = "make dev"
path = "~/Documents/Code/my-project/bpkb/bisma_be_dev"

[[window]]
name = "database"
path = "~/Documents/Code/my-project/bpkb/bisma_be_dev"

[[window]]
name = "bisma_fe"
path = "~/Documents/Code/my-project/bpkb/bisma_fe"
startup_script = "npm run build && npm run start"

[[window]]
name = "bisma_old"
path = "~/Documents/Code/my-project/bpkb/bisma_old"


# AXIS
[[session]]
name = "axis"
path = "~/Documents/Code/antikode/axis-mw"
startup_command = "update_tmux_window_name"
windows = ["server", "axis-cms"]

[[window]]
name = "server"
path = "~/Documents/Code/antikode/axis-mw"
startup_script = "make dev"

[[window]]
name = "axis-cms"
path = "~/Documents/Code/antikode/axis-cms"
startup_script = "git checkout release && git pull origin release"


# LAKASIR
[[session]]
name = "lakasir-project"
path = "~/Documents/Code/lakasir-project/lakasir"
startup_command = "update_tmux_window_name"
windows = ["lakasir_flutter"]

[[window]]
name = "lakasir_flutter"
path = "~/Documents/Code/lakasir-project/lakasir_flutter"


# ANTIKODE
[[session]]
name = "antikode"
path = "~/Documents/Code/antikode/agung-toyota-cms"
startup_command = "update_tmux_window_name"
windows = ["artotel-cms", "kahf-cms", "anticms-v3", "compass-nfc"]

[[window]]
name = "artotel-cms"
path = "~/Documents/Code/antikode/artotel-cms"

[[window]]
name = "kahf-cms"
path = "~/Documents/Code/antikode/kahf-cms"

[[window]]
name = "anticms-v3"
path = "~/Documents/Code/antikode/anticms-v3"

[[window]]
name = "compass-nfc"
path = "~/Documents/Code/antikode/compass-nfc"


# ASTRA
[[session]]
name = "astra"
path = "~/Documents/Code/antikode/astra/astra-dashboard"
startup_command = "update_tmux_window_name"
windows = ["sia-penjurian"]

[[window]]
name = "sia-penjurian"
path = "~/Documents/Code/antikode/astra/sia-penjurian"

# FUN
[[session]]
name = "fun"
path = "~/Documents/Code/dotfiles"
startup_command = "update_tmux_window_name"
