# source /usr/share/powerline/bindings/tmux/powerline.conf
# fast tmux esc in vim
set-option -s escape-time 1

set -g @plugin 'odedlaz/tmux-onedark-theme'
set -g @onedark_date_format "%Y-%m-%d"
# set -g @plugin 'egel/tmux-gruvbox'
# set -g @tmux-gruvbox 'dark' # or 'light'

# set 256 color
set -g default-terminal "screen-256color"

# status bar configuration
set -g status-right '%h-%d %H:%M '
# set -g status-left ''
# et -g status-bg '#383A59' 
# set -g status-fg 'white' 
# set -g display-panes-colour white
# set -g pane-active-border-style fg=#383A59,bg=default

# set-option -g display-panes-active-colour colour33 #blue
# set-option -g display-panes-colour colour166 #orange

set -g status off

set-window-option -g mode-keys vi
bind-key t set-option status
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

set -g @plugin 'christoomey/vim-tmux-navigator'

set-option -g status-position top
set-option -g default-shell /bin/zsh
set-option -g mouse on

run -b '~/.tmux/plugins/tpm/tpm'
