local cmd = vim.cmd  -- to execute Vim commands e.g. cmd('pwd')
local set = vim.o

cmd 'colorscheme default'
set.fileencodings="utf-8"
set.showmode=true
set.guicursor="n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20"
-- set.guicursor=""
set.ttyfast=true
set.compatible=false
set.swapfile=false
set.hlsearch=true
set.backspace="indent,eol,start"
set.wrap=false
set.encoding="utf-8"
set.pumheight=10
set.fileencoding="utf-8"
set.ruler=false
set.mouse=""
set.splitbelow=true
set.splitright=true
set.conceallevel=0
set.shiftwidth=2
set.smartindent=true
set.autoindent=true
set.expandtab=true
set.number=true
set.relativenumber=true
set.updatetime=300
set.timeoutlen=0
set.wildmenu=true
set.cursorline=false
set.cursorcolumn=false
set.backup=false
set.writebackup=false
set.list=true
set.lazyredraw=true
cmd 'highlight WinSparator guibg=None'
set.termguicolors=true
set.laststatus=3
-- set.foldmethod=expr
-- set.foldexpr=nvim_treesitter#foldexpr()
